apiVersion: v1
kind: Namespace
metadata:
  name: learn-code

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: learn-code
  name: replicaSet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eureka
    matchExpressions:
      - key: app
        operator: In
        values:
          - eureka
  template:
    metadata:
      namespace: learn-code
      name: eureka
      labels:
        creation_method: eureka
        env: dev
        app: eureka
    spec:
      nodeSelector:
        gpu: "true"
      containers:
        - image: eureka:1.0.0
          name: eureka
          livenessProbe:
            httpGet:
              port: 8761
              path: /
          ports:
            - containerPort: 8761
              protocol: TCP

---

apiVersion: v1
kind: Pod
metadata:
  namespace: learn-code
  name: eureka
  labels:
    creation_method: eureka
    env: dev
    app: eureka
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: eureka:1.0.0
    name: eureka
    livenessProbe:
      httpGet:
        port: 8761
        path: /
    ports:
      - containerPort: 8761
        protocol: TCP

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-job
spec:
  schedule: "0,15,31,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: learn-code
          name: eureka
          labels:
            creation_method: eureka
            env: dev
            app: eureka
        spec:
          containers:
            - image: eureka:1.0.0
              name: eureka
              livenessProbe:
                httpGet:
                  port: 8761
                  path: /
              ports:
                - containerPort: 8761
                  protocol: TCP